"""Add customer, cash, order, holding, transaction and market tables

Revision ID: 05d0d8db0ebb
Revises: a0fe3d1d0dca
Create Date: 2026-09-15 11:10:16.338157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d0d8db0ebb'
down_revision = 'a0fe3d1d0dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_username'), ['username'], unique=True)

    op.create_table('market_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.CheckConstraint('opening_time < closing_time', name='ck_market_hours_open_before_close'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulated_date', sa.Date(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulated_date')
    )
    op.create_table('cash_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_cash_accounts_balance_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint("order_type IN ('Buy', 'Sell')", name='ck_orders_order_type'),
    sa.CheckConstraint("status IN ('Pending', 'Executed', 'Cancelled', 'Rejected')", name='ck_orders_status'),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_stock_id'), ['stock_id'], unique=False)

    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('share_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('share_quantity >= 0', name='ck_portfolio_holdings_quantity_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'stock_id', name='uq_portfolio_holdings_customer_stock')
    )
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_holdings_stock_id'), ['stock_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('resulting_cash_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('share_quantity', sa.Integer(), nullable=True),
    sa.Column('price_per_share', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("transaction_type IN ('Deposit', 'Withdrawal', 'Buy', 'Sell')", name='ck_transactions_type'),
    sa.CheckConstraint('amount <> 0', name='ck_transactions_amount_non_zero'),
    sa.CheckConstraint('resulting_cash_balance >= 0', name='ck_transactions_resulting_balance_non_negative'),
    sa.CheckConstraint('share_quantity IS NULL OR share_quantity > 0', name='ck_transactions_share_quantity_positive'),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_cash_account_id'), ['cash_account_id'], unique=False)
        batch_op.create_index('ix_transactions_customer_date', ['customer_id', 'transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_stock_id'), ['stock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_stock_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_order_id'))
        batch_op.drop_index('ix_transactions_customer_date')
        batch_op.drop_index(batch_op.f('ix_transactions_cash_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_holdings_stock_id'))

    op.drop_table('portfolio_holdings')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_stock_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))

    op.drop_table('orders')
    op.drop_table('cash_accounts')
    op.drop_table('market_schedule')
    op.drop_table('market_hours')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_username'))

    op.drop_table('customers')
    # ### end Alembic commands ###
