"""Add price history

Revision ID: a0fe3d1d0dca
Revises: cfce6032d4e1
Create Date: 2026-09-01 10:30:15.531828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fe3d1d0dca'
down_revision = 'cfce6032d4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('simulated_datetime', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_simulated_datetime'), ['simulated_datetime'], unique=False)
        batch_op.create_index('ix_price_history_stock_datetime', ['stock_id', 'simulated_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_stock_id'), ['stock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_stock_id'))
        batch_op.drop_index('ix_price_history_stock_datetime')
        batch_op.drop_index(batch_op.f('ix_price_history_simulated_datetime'))

    op.drop_table('price_history')
    # ### end Alembic commands ###
