"""Add simulated market clock

Revision ID: cfce6032d4e1
Revises: f2c3db457aa5
Create Date: 2026-08-31 20:46:55.108690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfce6032d4e1'
down_revision = 'f2c3db457aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_clock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulated_anchor', sa.DateTime(), nullable=False),
    sa.Column('real_anchor', sa.DateTime(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('speed_multiplier', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_clock')
    # ### end Alembic commands ###
