"""Create stocks table

Revision ID: f2c3db457aa5
Revises: 
Create Date: 2026-08-31 10:35:13.841758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c3db457aa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('initial_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_ticker'), ['ticker'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_ticker'))

    op.drop_table('stocks')
    # ### end Alembic commands ###
